#!/bin/bash

# miguelvidalbellido

# Comprobamos que estamos en la rama hotfix
if [[ "$(git rev-parse --abbrev-ref HEAD)" != "hotfix" ]]; then
  echo "No en rama hotfix, continuando..."
  exit 0
fi

# Recuperamos el mensaje del commit del archivo proporcionado por Git
commit_message=$(<"$1")

# Comprobamos que el commit contiene la frase "A corregir por: ..."
if [[ "${commit_message}" != *"A corregir por: ..."* ]]; then
  echo "El mensaje de commit debe contener la siguiente frase 'A corregir por: ...'"
  exit 1
fi

echo "Mensaje de commit válido."
exit 0